### ISSUE TITLE
D&D 5e 0.99 PC Sheet Incompatibility

### ISSUE THREAD

**Issue by VoltCruelerz** [sdenec/tidy5e-sheet#121]
## Description
After upgrading D&D 5e to 0.99, I can no longer open any PC character sheets.  I assume there was some underlying data structure change, and this mod will need to be updated.

The following error is thrown in the logs:

```
TypeError: An error occurred while rendering Tidy5eSheet 38: (i.data.quantity * i.data.weight).toNearest is not a function
    at Tidy5eSheet._prepareItems (character.js:105)
    at Tidy5eSheet.getData (base.js:106)
    at Tidy5eSheet.getData (character.js:29)
    at Tidy5eSheet._render (foundry.js:4434)
    at Tidy5eSheet._render (foundry.js:5088)
    at Tidy5eSheet._render (foundry.js:16570)
    at Tidy5eSheet.render (foundry.js:4404)
    at Tidy5eSheet.render (foundry.js:5553)
    at Token._onClickLeft2 (foundry.js:44654)
    at MouseInteractionManager.callback (foundry.js:35797)
```

As I cannot open them, I cannot even change them to use a different character sheet.

## Mitigation Attempts
* Disabling all mods did not resolve, though it did cause the error in the logs to say the default 5e sheet instead of Tidy5eSheet.  
* Reverting to D&D 5e 0.98 resolved the issue.

**Comment by akrigline** [comment]
@VoltCruelerz What other modules do you usually have installed in this world? I am able to open the Tidy Sheet in a world with only dnd5e 0.99 and tidy sheet active.

**Comment by akrigline** [comment]
Looking at the error stack there I suspect this was a problem that got hotfixed in either dnd5e 0.99 or foundry 0.7.6, can you try either force updating the 0.7.6 update to get the hotfix, or reinstalling dnd5e 0.99?

**Comment by sdenec** [comment]
first of all it is vital, that you have 0.76 installed BEFORE you update to 0.99 5e system or else it messes up your data structure. This was stated by Atropos in the update notes for 0.99. Second - the tidy sheet works with the updated versio though there still have to be made adjustements to refelct the changes made to the new 0.99 core features. this will come as soon as possible.

**Comment by VoltCruelerz** [comment]
Ah, ok.  It was just that I didn't have 0.7.6 installed yet.
